### ISSUE TITLE
respond_with fails silenty on non-existing templates

### ISSUE THREAD

**Issue by gioele** [sinatra/sinatra-contrib#147]
`respond_with` will fail silently if a non-existing template name is supplied. It would be better to raise an exception if no acceptable template file can be found.

This simple test case will return an empty body while it should raise an exception.

```ruby
require 'sinatra'
require 'sinatra/respond_with'

register Sinatra::RespondWith

get '/foo' do
    data = { :foo => 'bar' }
    respond_with :idontexist, data
end
```

**Comment by ashleygwilliams** [comment]
confirmed locally. doesn't fail *completely* silently, returns a 406.

**Comment by ashleygwilliams** [comment]
after discussion with @zzak, we've decided this should 404 now and in the next minor release should raise an exception.

**Comment by TrevorBramble** [comment]
@ashleygwilliams Totally agree with this direction.

**Comment by zzak** [comment]
Ugh, so the problem with this change is we already have existing behavior when no template is found:

```
  1) Sinatra::RespondWith Helpers#respond_with templates does not use name.engine for engines producing other formats
     Failure/Error: status.should == 406
       expected: 406
            got: 404 (using ==)
     # ./spec/respond_with_spec.rb:207:in `block (4 levels) in <top (required)>'

  2) Sinatra::RespondWith Helpers#respond_with templates falls back to #json if no template is found
     Failure/Error: req(:json).should be_ok
       expected ok? to return true, got false
     # ./spec/respond_with_spec.rb:213:in `block (4 levels) in <top (required)>'

  3) Sinatra::RespondWith Helpers#respond_with templates falls back to to_EXT if no template is found
     Failure/Error: req(:pdf).should be_ok
       expected ok? to return true, got false
     # ./spec/respond_with_spec.rb:227:in `block (4 levels) in <top (required)>'
```

I don't think we should try to change this now. /cc @ashleygwilliams @TrevorBramble

**Comment by zzak** [comment]
FWIW, here is the patch that I was using:

```diff
diff --git a/lib/sinatra/respond_with.rb b/lib/sinatra/respond_with.rb
index 28f2107..ee1d2e1 100644
--- a/lib/sinatra/respond_with.rb
+++ b/lib/sinatra/respond_with.rb
@@ -145,6 +145,8 @@ module Sinatra
               options = args[1..-1] + [{:locals => locals}]
 
               halt send(renderer, *options)
+            else
+              halt 404
             end
           end
           if object
diff --git a/spec/respond_with_spec.rb b/spec/respond_with_spec.rb
index 18344fc..375126c 100644
--- a/spec/respond_with_spec.rb
+++ b/spec/respond_with_spec.rb
@@ -235,6 +235,12 @@ describe Sinatra::RespondWith do
           body.should == "\"yajl!\""
         end
       end
+
+      it 'results in a 404 if template cannot be found' do
+        respond_with :not_found
+        req(:html).should_not be_ok
+        status.should == 404
+      end
     end
 
     describe 'customizing' do
```
