### ISSUE TITLE
Ruby 2.3: Thread.exclusive is deprecated, use Mutex

### ISSUE THREAD

**Issue by burgalon** [sinatra/sinatra-contrib#183]
```
Thread.exclusive is deprecated, use Mutex
/Users/burg/.rvm/gems/ruby-2.3.0/gems/sinatra-contrib-1.4.6/lib/sinatra/reloader.rb:222:in `block in registered'
/Users/burg/.rvm/gems/ruby-2.3.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1610:in `call'
/Users/burg/.rvm/gems/ruby-2.3.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1610:in `block in compile!'
/Users/burg/.rvm/gems/ruby-2.3.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1014:in `block in process_route'
/Users/burg/.rvm/gems/ruby-2.3.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1012:in `catch'
/Users/burg/.rvm/gems/ruby-2.3.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1012:in `process_route'
/Users/burg/.rvm/gems/ruby-2.3.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:965:in `block in filter!'
/Users/burg/.rvm/gems/ruby-2.3.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:965:in `each'
/Users/burg/.rvm/gems/ruby-2.3.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:965:in `filter!'
/Users/burg/.rvm/gems/ruby-2.3.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1083:in `block in dispatch!'
/Users/burg/.rvm/gems/ruby-2.3.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `block in invoke'
/Users/burg/.rvm/gems/ruby-2.3.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `catch'
/Users/burg/.rvm/gems/ruby-2.3.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `invoke'
/Users/burg/.rvm/gems/ruby-2.3.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1081:in `dispatch!'
/Users/burg/.rvm/gems/ruby-2.3.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:906:in `block in call!'
/Users/burg/.rvm/gems/ruby-2.3.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `block in invoke'
/Users/burg/.rvm/gems/ruby-2.3.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `catch'
/Users/burg/.rvm/gems/ruby-2.3.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `invoke'
/Users/burg/.rvm/gems/ruby-2.3.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:906:in `call!'
/Users/burg/.rvm/gems/ruby-2.3.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:894:in `call'
/Users/burg/.rvm/gems/ruby-2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
/Users/burg/.rvm/gems/ruby-2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
/Users/burg/.rvm/gems/ruby-2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
/Users/burg/.rvm/gems/ruby-2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
/Users/burg/.rvm/gems/ruby-2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
/Users/burg/.rvm/gems/ruby-2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
/Users/burg/.rvm/gems/ruby-2.3.0/gems/rack-1.6.4/lib/rack/nulllogger.rb:9:in `call'
/Users/burg/.rvm/gems/ruby-2.3.0/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
/Users/burg/.rvm/gems/ruby-2.3.0/gems/sinatra-1.4.6/lib/sinatra/show_exceptions.rb:21:in `call'
/Users/burg/.rvm/gems/ruby-2.3.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:181:in `call'
/Users/burg/.rvm/gems/ruby-2.3.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:2021:in `call'
/Users/burg/.rvm/gems/ruby-2.3.0/gems/capybara-2.4.4/lib/capybara/server.rb:19:in `call'
/Users/burg/.rvm/gems/ruby-2.3.0/gems/rack-1.6.4/lib/rack/handler/webrick.rb:88:in `service'
/Users/burg/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/webrick/httpserver.rb:140:in `service'
/Users/burg/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/webrick/httpserver.rb:96:in `run'
/Users/burg/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/webrick/server.rb:296:in `block in start_thread'
```

**Comment by eterry1388** [comment]
:+1: I'm getting this too.

**Comment by kitplummer** [comment]
See the same with 'thin' web server.

**Comment by kitplummer** [comment]
Cool, is the #184 PR going to get fixed, to pass the tests and merged?

**Comment by mecampbellsoup** [comment]
:+1:

**Comment by mecampbellsoup** [comment]
In the interim, anyone know which Ruby version can be safely used?

**Comment by zzak** [comment]
I'll see about doing some triage and bug fix release for contrib asap.

**Comment by gudmundur** [comment]
Any chance on getting this issue resolved? These stack traces look rather scary and verbose during local development.

**Comment by zzak** [comment]
Right now the build is red, so I need to fix that before I can make a stable release.

**Comment by JMCQ87** [comment]
Thanks for looking into this. Having this stack trace on every request in your app is somewhat... inconvenient. ;)

**Comment by JMCQ87** [comment]
activerecord-session-store seems to have made a similar [change](https://github.com/rails/activerecord-session_store/commit/82a7540dd8095cf09fe4dd4966df2cf2001e56cb).

Could the same be applied here?

**Comment by JoeeGrigg** [comment]
Hi,
I am keep to upgrade to ruby 2.3.0.
Just wondering if there is any update on this issue being resolved?
:smile:

**Comment by rennhak** [comment]
+1

**Comment by gmcmillan** [comment]
Same issue here on Ruby 2.3.0 and Sinatra 1.4.5

**Comment by kch** [comment]
@rkh this is the issue that i mentioned is keeping @gudmundur upset

**Comment by gudmundur** [comment]
grr :)

**Comment by zzak** [comment]
[Shipped!](https://twitter.com/_zzak/status/719372332884557826)

Thanks for your patience :bow: :bow: :bow:

**Comment by gudmundur** [comment]
@zzak 👏  👏  👏 !

**Comment by rennhak** [comment]
@zzak Thank you so much!

**Comment by DouglasAllen** [comment]
I'm getting this from old version of Rack. Please update Sinatra to use the latest version soon. Thanks!
